### ISSUE TITLE
[Angular + Apollo + Tailwind] Fix Tailwind Prod Bundle Size

### ISSUE THREAD

**Issue by morgnism** [thisdot/starter.dev-github-showcases#160]

**Comment by BrettZeidler** [comment]
Is it necessary to further optimize the bundle size? And/or has someone resolved this since the issue was originally opened?

Current bundle size with specified purge in `tailwind.config.js`:
<img width="424" alt="Screen Shot 2022-05-06 at 3 02 54 PM" src="https://user-images.githubusercontent.com/54006458/167209715-6e3b23d6-55a9-4f5f-a0e7-d4aff01b8cd8.png">

Without the purge:
<img width="420" alt="Screen Shot 2022-05-06 at 3 02 21 PM" src="https://user-images.githubusercontent.com/54006458/167209755-5f2e65c0-a922-48ec-ad6d-e99a765f0625.png">

Is it necessary to try to push further than under 12.92KB for the bundled styles?

**Comment by morgnism** [comment]
There were warnings before about the size. This was blocking the build when we first went to prod, but if you're not seeing that now I'll close this one.
