### ISSUE TITLE
[vue3-apollo-quasar] Architectural review of current kit & showcase and any cleanup recommendations

### ISSUE THREAD

**Issue by dustinsgoodman** [thisdot/starter.dev-github-showcases#519]

**Comment by AllanJeremy** [comment]
## README
The[ current README.md file](https://github.com/thisdot/starter.dev-github-showcases/blob/main/vue3-apollo-quasar/README.md) in the main branch only contains the bare minimum for running the application. There is [a slightly more detailed version here](https://github.com/thisdot/starter.dev-github-showcases/blob/vue3-ts-quasar/documentation/vue3-ts-quasar/README.md) but it also lacks in some areas:
- Architectural choices
- Coding style

## Storybook
- We need to get rid of the example storybooks:
![Image](https://user-images.githubusercontent.com/5031274/185591178-da6d4d2a-f0b0-4c7a-8925-87863c1361cf.png)

- In some cases, we get an "Apollo client not available" in the following stories:
![Image](https://user-images.githubusercontent.com/5031274/185591076-6f60f352-1524-428b-9a5e-0399a129963e.png)
	- [GistsPanel.stories.ts](https://github.com/thisdot/starter.dev-github-showcases/blob/main/vue3-apollo-quasar/src/components/GistsPanel/GistsPanel.stories.ts "GistsPanel.stories.ts")
	- [NavHeader.stories.ts](https://github.com/thisdot/starter.dev-github-showcases/blob/main/vue3-apollo-quasar/src/components/NavHeader/NavHeader.stories.ts "NavHeader.stories.ts")

- Profile related stories do not load profile data in stories
	- This is because they try making a request to the github graphql API which ends up being unauthorized. That means the story that should contain profile information (username, profile pic) ends up blank.

**Comment by AllanJeremy** [comment]
## Home page
![Image](https://user-images.githubusercontent.com/5031274/185594941-56ccdb11-e01c-4885-acd6-1192dd632439.png)
- [ ] Repository link does nothing: this should redirect to the appropriate repo route
- [ ]Star button on the right does nothing
- [ ]Stargazers count is text instead of being a link that redirects to stargazers for a given repo
- [ ]Missing network member count in repo details at the bottom. This should also be a link that redirects to the repo's members. Here's how it should ideally look:
    ![Image](https://user-images.githubusercontent.com/5031274/185595164-2ac6c5dd-11cd-4657-9fbb-970bbdf2466e.png)

- [ ] The view repositories button redirects to a URL (`/profile`) that resolves to a github profile corresponding to a GitHub username called `profile` rather than showing the actual users' profile. 
The fix for this (assuming the url remains unchanged) is to add a special route `/profile` or equivalent that specifically checks for the current user rather than assuming that `profile` is the `username` we want to load a profile for.

## Navigation
![Image](https://user-images.githubusercontent.com/5031274/185595442-a696778d-d8f8-4f2e-9168-c3efac61ab8e.png)
Only the Profile link in the top navigation menu works. The following links have incorrect redirects:
- [ ] Repositories
- [ ] Gists
- [ ] Organizations

**Comment by AllanJeremy** [comment]
## Profile page
- [ ] Profile information does not update under certain conditions
  - [ ] If the current URL is already a profile page, for example: [http://localhost:8080/LinusTorvalds](http://localhost:8080/LinusTorvalds) then clicking the Profile link in the nav menu does not load the current user's profile and stays on the existing profile. A possible reason for this is because we are loading profile information on page load/mount and since we are already on the  page we want to load information on, the request to load a different profile is not made. Potential solutions to this would be:
  - [ ]  Update the `username` along with any other profile information **on route change** rather than page load in `ProfilePageLayout.vue`.
- [ ] Visiting a non-existent profile should redirect to 404. Currently shows a blank profile page


![Image](https://user-images.githubusercontent.com/5031274/185600587-51d6674e-c789-46db-a608-64a105eb3b31.png)

### Profile details
- [ ] Various profile links don't work
![Image](https://user-images.githubusercontent.com/5031274/185600800-a0066c8c-f6c0-4466-8bdf-cf48fe9aef57.png)
  - [ ] Followers link doesn't work
  - [ ] Following link doesn't work
  - [ ] Stars link doesn't work
  - [ ] Twitter link redirects to incorrect URL (looks like an incorrectly parsed URL. Can be fixed in `UserProfileCard.vue`)
![Image](https://user-images.githubusercontent.com/5031274/185601002-49156604-5e40-4050-8bd9-77d1203830d4.png)


### Repositories tab
- [ ] Search doesn't work
- [ ] Some repo filter options don't work
  - [ ] Type filter doesn't work
  - [ ] Sort filter doesn't work





- [ ] Repo specific components are visible even when visiting non-repository tabs

![Image](https://user-images.githubusercontent.com/5031274/185600751-802279f1-ad80-44f1-b5c3-00655939082c.png)

**Comment by AllanJeremy** [comment]
## Loading Skeletons
Multiple pages could benefit from showing a skeleton while loading data but currently don't:
- [ ] Home page
  - [ ] Gists list
  - [ ] Top repositories
- [ ] Profile page
  - [ ] Repository list

Why would we want to do this? Mostly to show the user that something is happening and prevent things from jumping around the relevant data is eventually loaded.

**Comment by honzikec** [comment]
> ## Home page
> ![Image](https://user-images.githubusercontent.com/5031274/185594941-56ccdb11-e01c-4885-acd6-1192dd632439.png)
> 
> * [ ]  Repository link does nothing: this should redirect to the appropriate repo route
> * [ ]  Star button on the right does nothing
> * [ ]  Stargazers count is text instead of being a link that redirects to stargazers for a given repo
> * [ ]  Missing network member count in repo details at the bottom. This should also be a link that redirects to the repo's members. Here's how it should ideally look:
>   ![Image](https://user-images.githubusercontent.com/5031274/185595164-2ac6c5dd-11cd-4657-9fbb-970bbdf2466e.png)
> * [ ]  The view repositories button redirects to a URL (`/profile`) that resolves to a github profile corresponding to a GitHub username called `profile` rather than showing the actual users' profile.
> 
> ![Image](https://user-images.githubusercontent.com/5031274/185596922-4fcba021-9d1e-4d5a-905f-a6134cf6be0d.png)
> 
> The fix for this we can simply redirect to the currently logged in user's profile (same navigation as clicking `profile` in the nav menu)
> 
> ## Navigation
> ![Image](https://user-images.githubusercontent.com/5031274/185595442-a696778d-d8f8-4f2e-9168-c3efac61ab8e.png) Only the Profile link in the top navigation menu works. The following links have incorrect redirects:
> 
> * [ ]  Repositories
> * [ ]  Gists
> * [ ]  Organizations

@AllanJeremy fyi - the repo link should be solved in https://github.com/thisdot/starter.dev-github-showcases/pull/523

**Comment by AllanJeremy** [comment]
First off, thanks for the heads up @honzikec ! Once it is resolved on this end we could check it as done here.

## Code
- [ ] GraphQL query results are not typed. Calls to `useQuery` should specify what the expected return type of the query is. This would allow us to take advantage of type safety offered by TS.

--
Ran out of time before being able to do an extensive code review but for the most part I think these can be covered in the architecture part of the documentation.
