### ISSUE TITLE
[Showcases API] Include Repo Tree Structure For Deeper Paths

### ISSUE THREAD

**Issue by kenslachtajr** [thisdot/starter.dev-github-showcases#893]
# Acceptance Criteria

- The `contents` call is specific to the root, but takes an optional “path” query to get the tree structure for deeper paths
- Tree structure: /repos/${owner}/${repoName}/contents

**Comment by mbicknese** [comment]
Hi Ken, can you point me in the right direction on how to get started on this ticket?

**Comment by jtomchak** [comment]
So. The frontend showcases are making requests directly to the github api like the one below to get tree structure of the repo with file/folder names to display for the FileExplore part of the app. The idea is since we have a backend gql of our own, can we datasource of these calls to make it easier on the frontend? 

![Google Chrome 2023-01-04 at 08 55 19@2x](https://user-images.githubusercontent.com/76360/210595766-c2dc0dfc-7636-492b-9d3d-174f72be729b.png)

From the image above there is a single fetch for the structure every time the user clicks on a folder. They click, we fetch. They click, we fetch. The red arrows are every time I click a folder in the repo, it fetches that data, then loads/renders it. 😴 

## The Ask
Can we, using our own gql datasource make this a better experience? For instance, the client calls our gql endpoint for a repo and we return the entire tree structure of all the file names of that directory, **and** the nested folder/files from there down. So that _on route_ to a nested directory (when the user clicks) the frontend already has the data and loads instantly?

```
    query RepoTree($owner: String!, $name: String!, $expression: String!) {
  repository(owner: $owner, name: $name) {
    branches: refs(refPrefix: "refs/heads/", last: 5) {
      nodes {
        name
      }
    }
    tree: object(expression: $expression) {
      ... on Tree {
        entries {
          name
          type
          path
        }
      }
    }
  }
}
   
```
With Variables: 
```
{
    "owner": "mediadevelopers",
    "name": "media-jams",
    "expression": "main:"
}
```

**Comment by jtomchak** [comment]
This gist has a starting point, https://gist.github.com/MichaelCurrin/6777b91e6374cdb5662b64b8249070ea

**Comment by jtomchak** [comment]
Or at the very least cache it so we don't have to keep calling github over and over for the same info, but rather serve it up from our cache?
